package url

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new url API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for url API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
UrlshortenerURLGet Expands a short URL or gets creation time and analytics.
*/
func (a *Client) UrlshortenerURLGet(params *UrlshortenerURLGetParams, authInfo runtime.ClientAuthInfoWriter) (*UrlshortenerURLGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUrlshortenerURLGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "urlshortener.url.get",
		Method:             "GET",
		PathPattern:        "/url",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UrlshortenerURLGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UrlshortenerURLGetOK), nil

}

/*
UrlshortenerURLInsert Creates a new short URL.
*/
func (a *Client) UrlshortenerURLInsert(params *UrlshortenerURLInsertParams, authInfo runtime.ClientAuthInfoWriter) (*UrlshortenerURLInsertOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUrlshortenerURLInsertParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "urlshortener.url.insert",
		Method:             "POST",
		PathPattern:        "/url",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UrlshortenerURLInsertReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UrlshortenerURLInsertOK), nil

}

/*
UrlshortenerURLList Retrieves a list of URLs shortened by a user.
*/
func (a *Client) UrlshortenerURLList(params *UrlshortenerURLListParams, authInfo runtime.ClientAuthInfoWriter) (*UrlshortenerURLListOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUrlshortenerURLListParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "urlshortener.url.list",
		Method:             "GET",
		PathPattern:        "/url/history",
		ProducesMediaTypes: []string{""},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UrlshortenerURLListReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UrlshortenerURLListOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
