package url

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-googl/models"
)

// NewUrlshortenerURLInsertParams creates a new UrlshortenerURLInsertParams object
// with the default values initialized.
func NewUrlshortenerURLInsertParams() *UrlshortenerURLInsertParams {
	var (
		altDefault         = string("json")
		prettyPrintDefault = bool(true)
	)
	return &UrlshortenerURLInsertParams{
		Alt:         &altDefault,
		PrettyPrint: &prettyPrintDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewUrlshortenerURLInsertParamsWithTimeout creates a new UrlshortenerURLInsertParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUrlshortenerURLInsertParamsWithTimeout(timeout time.Duration) *UrlshortenerURLInsertParams {
	var (
		altDefault         = string("json")
		prettyPrintDefault = bool(true)
	)
	return &UrlshortenerURLInsertParams{
		Alt:         &altDefault,
		PrettyPrint: &prettyPrintDefault,

		timeout: timeout,
	}
}

// NewUrlshortenerURLInsertParamsWithContext creates a new UrlshortenerURLInsertParams object
// with the default values initialized, and the ability to set a context for a request
func NewUrlshortenerURLInsertParamsWithContext(ctx context.Context) *UrlshortenerURLInsertParams {
	var (
		altDefault         = string("json")
		prettyPrintDefault = bool(true)
	)
	return &UrlshortenerURLInsertParams{
		Alt:         &altDefault,
		PrettyPrint: &prettyPrintDefault,

		Context: ctx,
	}
}

/*UrlshortenerURLInsertParams contains all the parameters to send to the API endpoint
for the urlshortener url insert operation typically these are written to a http.Request
*/
type UrlshortenerURLInsertParams struct {

	/*Alt
	  Data format for the response.

	*/
	Alt *string
	/*Body*/
	Body *models.URL
	/*Fields
	  Selector specifying which fields to include in a partial response.

	*/
	Fields *string
	/*Key
	  API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.

	*/
	Key *string
	/*OauthToken
	  OAuth 2.0 token for the current user.

	*/
	OauthToken *string
	/*PrettyPrint
	  Returns response with indentations and line breaks.

	*/
	PrettyPrint *bool
	/*QuotaUser
	  Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.

	*/
	QuotaUser *string
	/*UserIP
	  IP address of the site where the request originates. Use this if you want to enforce per-user limits.

	*/
	UserIP *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithTimeout(timeout time.Duration) *UrlshortenerURLInsertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithContext(ctx context.Context) *UrlshortenerURLInsertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithAlt adds the alt to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithAlt(alt *string) *UrlshortenerURLInsertParams {
	o.SetAlt(alt)
	return o
}

// SetAlt adds the alt to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetAlt(alt *string) {
	o.Alt = alt
}

// WithBody adds the body to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithBody(body *models.URL) *UrlshortenerURLInsertParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetBody(body *models.URL) {
	o.Body = body
}

// WithFields adds the fields to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithFields(fields *string) *UrlshortenerURLInsertParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetFields(fields *string) {
	o.Fields = fields
}

// WithKey adds the key to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithKey(key *string) *UrlshortenerURLInsertParams {
	o.SetKey(key)
	return o
}

// SetKey adds the key to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetKey(key *string) {
	o.Key = key
}

// WithOauthToken adds the oauthToken to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithOauthToken(oauthToken *string) *UrlshortenerURLInsertParams {
	o.SetOauthToken(oauthToken)
	return o
}

// SetOauthToken adds the oauthToken to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetOauthToken(oauthToken *string) {
	o.OauthToken = oauthToken
}

// WithPrettyPrint adds the prettyPrint to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithPrettyPrint(prettyPrint *bool) *UrlshortenerURLInsertParams {
	o.SetPrettyPrint(prettyPrint)
	return o
}

// SetPrettyPrint adds the prettyPrint to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetPrettyPrint(prettyPrint *bool) {
	o.PrettyPrint = prettyPrint
}

// WithQuotaUser adds the quotaUser to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithQuotaUser(quotaUser *string) *UrlshortenerURLInsertParams {
	o.SetQuotaUser(quotaUser)
	return o
}

// SetQuotaUser adds the quotaUser to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetQuotaUser(quotaUser *string) {
	o.QuotaUser = quotaUser
}

// WithUserIP adds the userIP to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) WithUserIP(userIP *string) *UrlshortenerURLInsertParams {
	o.SetUserIP(userIP)
	return o
}

// SetUserIP adds the userIp to the urlshortener url insert params
func (o *UrlshortenerURLInsertParams) SetUserIP(userIP *string) {
	o.UserIP = userIP
}

// WriteToRequest writes these params to a swagger request
func (o *UrlshortenerURLInsertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Alt != nil {

		// query param alt
		var qrAlt string
		if o.Alt != nil {
			qrAlt = *o.Alt
		}
		qAlt := qrAlt
		if qAlt != "" {
			if err := r.SetQueryParam("alt", qAlt); err != nil {
				return err
			}
		}

	}

	if o.Body == nil {
		o.Body = new(models.URL)
	}

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if o.Fields != nil {

		// query param fields
		var qrFields string
		if o.Fields != nil {
			qrFields = *o.Fields
		}
		qFields := qrFields
		if qFields != "" {
			if err := r.SetQueryParam("fields", qFields); err != nil {
				return err
			}
		}

	}

	if o.Key != nil {

		// query param key
		var qrKey string
		if o.Key != nil {
			qrKey = *o.Key
		}
		qKey := qrKey
		if qKey != "" {
			if err := r.SetQueryParam("key", qKey); err != nil {
				return err
			}
		}

	}

	if o.OauthToken != nil {

		// query param oauth_token
		var qrOauthToken string
		if o.OauthToken != nil {
			qrOauthToken = *o.OauthToken
		}
		qOauthToken := qrOauthToken
		if qOauthToken != "" {
			if err := r.SetQueryParam("oauth_token", qOauthToken); err != nil {
				return err
			}
		}

	}

	if o.PrettyPrint != nil {

		// query param prettyPrint
		var qrPrettyPrint bool
		if o.PrettyPrint != nil {
			qrPrettyPrint = *o.PrettyPrint
		}
		qPrettyPrint := swag.FormatBool(qrPrettyPrint)
		if qPrettyPrint != "" {
			if err := r.SetQueryParam("prettyPrint", qPrettyPrint); err != nil {
				return err
			}
		}

	}

	if o.QuotaUser != nil {

		// query param quotaUser
		var qrQuotaUser string
		if o.QuotaUser != nil {
			qrQuotaUser = *o.QuotaUser
		}
		qQuotaUser := qrQuotaUser
		if qQuotaUser != "" {
			if err := r.SetQueryParam("quotaUser", qQuotaUser); err != nil {
				return err
			}
		}

	}

	if o.UserIP != nil {

		// query param userIp
		var qrUserIP string
		if o.UserIP != nil {
			qrUserIP = *o.UserIP
		}
		qUserIP := qrUserIP
		if qUserIP != "" {
			if err := r.SetQueryParam("userIp", qUserIP); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
