package url

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-googl/models"
)

// UrlshortenerURLListReader is a Reader for the UrlshortenerURLList structure.
type UrlshortenerURLListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UrlshortenerURLListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUrlshortenerURLListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUrlshortenerURLListOK creates a UrlshortenerURLListOK with default headers values
func NewUrlshortenerURLListOK() *UrlshortenerURLListOK {
	return &UrlshortenerURLListOK{}
}

/*UrlshortenerURLListOK handles this case with default header values.

Successful response
*/
type UrlshortenerURLListOK struct {
	Payload *models.URLHistory
}

func (o *UrlshortenerURLListOK) Error() string {
	return fmt.Sprintf("[GET /url/history][%d] urlshortenerUrlListOK  %+v", 200, o.Payload)
}

func (o *UrlshortenerURLListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.URLHistory)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
