package url

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-googl/models"
)

// UrlshortenerURLInsertReader is a Reader for the UrlshortenerURLInsert structure.
type UrlshortenerURLInsertReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UrlshortenerURLInsertReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUrlshortenerURLInsertOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUrlshortenerURLInsertOK creates a UrlshortenerURLInsertOK with default headers values
func NewUrlshortenerURLInsertOK() *UrlshortenerURLInsertOK {
	return &UrlshortenerURLInsertOK{}
}

/*UrlshortenerURLInsertOK handles this case with default header values.

Successful response
*/
type UrlshortenerURLInsertOK struct {
	Payload *models.URL
}

func (o *UrlshortenerURLInsertOK) Error() string {
	return fmt.Sprintf("[POST /url][%d] urlshortenerUrlInsertOK  %+v", 200, o.Payload)
}

func (o *UrlshortenerURLInsertOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.URL)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
