package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/olebedev/go-googl/client/url"
)

// Default URL shortener HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new URL shortener HTTP client.
func NewHTTPClient(formats strfmt.Registry) *URLShortener {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("www.googleapis.com", "/urlshortener/v1", []string{"https"})
	return New(transport, formats)
}

// New creates a new URL shortener client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *URLShortener {
	cli := new(URLShortener)
	cli.Transport = transport

	cli.URL = url.New(transport, formats)

	return cli
}

// URLShortener is a client for URL shortener
type URLShortener struct {
	URL *url.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *URLShortener) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.URL.SetTransport(transport)

}
