package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// StringCount string count
// swagger:model StringCount
type StringCount struct {

	// Number of clicks for this top entry, e.g. for this particular country or browser.
	Count int64 `json:"count,omitempty"`

	// Label assigned to this top entry, e.g. "US" or "Chrome".
	ID string `json:"id,omitempty"`
}

// Validate validates this string count
func (m *StringCount) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
